triplanner/apps/sights/urls.py
from django.urls import path
from . import views

app_name = 'sights'

urlpatterns = [
    path('new', views.new, name='new'),
    path('create', views.create), # POST
    path('<int:sight_id>/edit', views.amend, name='edit'),
    path('<int:sight_id>/update', views.edit), # PUT
    path('<int:sight_id>/delete', views.remove), # DELETE

]

triplanner/apps/trips/urls.py
from django.urls import path
from . import views

app_name = 'trips'

urlpatterns = [
    path('', views.index, name='home'),
    path('new', views.new, name='new'),
    path('create', views.create), # POST
    path('<int:trip_id>/edit', views.amend, name='edit'),
    path('<int:trip_id>/update', views.edit), # PUT
    path('<int:trip_id>/delete', views.remove), # DELETE
    path('<int:trip_id>', views.access)

]

triplanner/apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('user/create', views.create), # POST
    path('user/registered', views.register, name='registered'),
    path('user/login', views.login) # POST

]

triplanner/triplanner/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.users.urls')),
    path('trips/', include('apps.trips.urls')),
    path('sights/', include('apps.sights.urls'))
    # path('admin/', admin.site.urls),
]

triplanner/apps/trips/models.py
from django.db import models
from ..users.models import User

# Create your models here.
class TripManager(models.Manager):
    def trip_validator(self, postData):
        errors = {}
        if len(postData['destination']) < 3:
            errors['destination'] = 'Destination must be at least 3 characters'
        if postData['transportation'] not in ['car', 'public', 'walk']:
            errors['transportation'] = 'Please select a valid mode of transportation'
        if len(postData['description']) < 3:
            errors['description'] = 'Description must be at least 3 characters'
        return errors

class Trip(models.Model):
    destination = models.CharField(max_length=100)
    transportation = models.CharField(max_length=50)
    description = models.TextField()
    organizer = models.ForeignKey(User, related_name="trips", on_delete=models.CASCADE) # join?
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = TripManager()

triplanner/apps/trips/views.py
from django.shortcuts import render, redirect
from django.db.models import Max
from django.contrib import messages
from .models import Trip
from ..users.models import User
from django.http import HttpResponse


transport = {'car': 'Car',
        'public': 'Public Transportation',
        'walk': 'Walking'}

# Create your views here.
# dashboard
def index(request):
    if 'user_id' not in request.session:
        return redirect('/')
    try:
        del request.session['edit_trip']
    except:
        pass
    try:
        del request.session['trip_id']
    except:
        pass
    context = {
        'all_trips': Trip.objects.all(),
        'transport': transport
    }
    return render(request, 'list.html', context)

# adding trip
def new(request):
    if 'user_id' not in request.session:
        return redirect('/')
    return render(request, 'form.html')

def create(request):
    errors = Trip.objects.trip_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/trips/new')
    else:
        # add create element
        organizer = User.objects.get(id=int(request.session['user_id']))
        new_trip = Trip.objects.create(
        destination = request.POST['destination'],
        transportation = request.POST['transportation'],
        description = request.POST['description'],
        organizer = organizer
        )
        
        return redirect('/trips')

# amending trip
def amend(request, trip_id):
    if 'user_id' not in request.session:
        return redirect('/')
    trip = Trip.objects.get(id=trip_id)
    if request.session['user_id'] != trip.organizer.id:
        return redirect('/trips')
    request.session['edit_trip'] = str(trip_id)
    context = {
        'trip': trip,
        'choices': transport
        }
    return render(request, 'form.html', context)

def edit(request, trip_id):
    trip_to_update = Trip.objects.get(id=trip_id)
    
    errors = Trip.objects.trip_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect(f'/trips/{trip_id}/edit')
    else:
    # add update element
        trip_to_update.destination = request.POST['destination']
        trip_to_update.transportation = request.POST['transportation']
        trip_to_update.description = request.POST['description']
        trip_to_update.save()
    
        return redirect('/trips')

def remove(request, trip_id):
    # delete trip
    trip_to_delete = Trip.objects.get(id=trip_id)
    trip_to_delete.delete()
    return redirect('/trips')

# view trip
def access(request, trip_id):
    if 'user_id' not in request.session:
        return redirect('/')
    try:
        del request.session['edit_sight']
    except:
        pass
    trip = Trip.objects.get(id=trip_id)
    # needed format for a for loop [[day,[events]],...]
    ordered_sights = []
    sights = trip.sights.all()
    max_day = 1
    if sights:
        max_day = (sights.aggregate(Max('day')))['day__max']
        for day in range(1,max_day + 1):
            routes = []
            sights_for_day = sights.filter(day=day).order_by('order')
            if sights_for_day:
                for sight in sights_for_day:
                    if sight == sights_for_day.first():
                        pass
                    else:
                        routes.append(sight)
                ending = {'name':'Hotel'}
                routes.append(ending)
                ordered_sights.append([day, zip(sights_for_day, routes)])
            else:
                ordered_sights.append([day,[]])
    else:
        ordered_sights.append([1,[]])

    

    # view trip
    context = {
        'trip': trip,
        'ordered_sights':ordered_sights,
        'max_day': max_day,
        'transport': transport[trip.transportation]
    }
    request.session['trip_id'] = trip_id
    return render(request, 'details.html', context)

triplanner/apps/trips/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <title>Triplanner - {{trip.destination}}</title>
</head>
<body>
    <header>
        <div class="d-flex justify-content-between my-2">
            <h1 class="display-1">Your Trip to {{trip.destination}}</h1>
            <p class="align-self-end"><a href="{% url 'trips:home' %}">Return to Home</a> | <a href="{% url 'users:index' %}">Logout</a></p>
        </div>
        {% if trip.organizer.id == request.session.user_id %}
            <a href="/trips/{{trip.id}}/edit" class="my-2">Edit Trip</a>
        {% else %}
            <p class="my-2">This trip is hosted by {{trip.organizer.name}}</p>
        {% endif %}
    </header>
    <main>
        <p class="trip_description my-2">{{trip.description}}</p>
        <p class="conditions mb-2">You are traveling to <strong>{{trip.destination}}</strong> for at least <strong>{{max_day}} days</strong>. You will be going around via <strong>{{transport}}</strong>.</p>
        <!-- <p class="italic">The timing below does not include commute time [from the hotel to the first event and the last event to the hotel (depending on belt)].</p> -->
        <a href="{% url 'sights:new' %}">Add Sight</a>
        <hr />
        {% for day, sight_list in ordered_sights %}
            <div class="day">
                {% if sight_list %}
                <div class="event_summary my-3">
                    <h3>Day {{day}} (Total hours: [Y] hours and [Z] Minutes)</h3>
                </div>
                <!-- for loop on events given day number of trip -->
                    <div class="events">
                        {% for sight, route in sight_list %}
                            <div class="event_details day border border-secondary my-1 p-4">
                                <div class="sight row">
                                    <label class="col-3" for="sight">Sight:</label>
                                    <p class="col-7">{{sight.name}}</p>
                                </div>
                                <div class="duration row">
                                    <label class="col-3" for="duration">Duration:</label>
                                    <p class="col-7">{{sight.duration}} minutes</p>
                                </div>
                                <div class="event_description row">
                                    <label class="col-3" for="description">Description:</label>
                                    <p class="col-7">{{sight.description}}</p>
                                </div>
                                <div class="creator row">
                                    <label class="col-3" for="creator">Creator:</label>
                                    <p class="col-7">{{sight.creator.name}}</p>
                                </div>
                                <div class="next row">
                                    <label class="col-3" for="next">Next Event:</label>
                                    <p class="col-7">{{route.name}}</p>
                                </div>
                                {% if sight.creator.id == request.session.user_id %}<p><a href="/sights/{{sight.id}}/edit">Edit</a> | <a href="/sights/{{sight.id}}/delete">Delete</a></p>{% endif %}
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="event_summary my-3">
                            <h3>Day {{day}}</h3>
                        </div>
                        <p class="text-muted">You don't have anything scheduled for this day!</p>
                    {% endif %}
                    </div>
                <!-- if going for black belt, have events for loop iterate till everything till last then add in the last component -->
            </div>
        {% endfor %}
    </main>
</body>
</html>

triplanner/apps/trips/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    {% if 'edit_trip' in request.session %}
        <title>Triplanner - Edit Trip</title>
    {% else %}
        <title>Triplanner - New Trip</title>
    {% endif %}
</head>
<body>
    <header class="d-flex justify-content-between my-4">
        {% if 'edit_trip' in request.session %}
            <h1 class="display-3">Edit Trip Info for {{trip.destination}}</h1>
        {% else %}
            <h1 class="display-1">New Trip</h1>
        {% endif %}
        <p class="align-self-end"><a href="{% url 'trips:home' %}">Return to Home</a>{% if 'edit_trip' in request.session %} | <a href="/trips/{{request.session.edit_trip}}">Return to Trip</a>{%endif%} | <a href="{% url 'users:index' %}">Logout</a></p>
    </header>
    <main>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="text-danger">{{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if 'edit_trip' in request.session %}
            <form action="/trips/{{ request.session.edit_trip }}/update" method="post">
        {% else %}
            <form action="/trips/create" method="post">
        {% endif %}
            {% csrf_token %}
            <div class="form-group row">
                <label class="col" type='text' name="destination">Destination:</label>
                <input class="col" type="text" name="destination" value="{{trip.destination}}">
            </div>
            <div class="form-group row">
                <label class="col" type='text' name="transportation">Mode of Transportation:</label>
                <select class="col" name="transportation">
                    <!-- for loop and if statement for selected value -->
                    {% if 'edit_trip' in request.session %}
                        {% for key, choice in choices.items %}
                            {% if key == trip.transportation %}
                                <option value="{{key}}" selected>{{choice}}</option>
                            {% else %}
                                <option value="{{key}}">{{choice}}</option>
                            {% endif %}
                        {% endfor %}                        
                    {% else %}
                        <option selected>Make a selection...</option>
                        <option value="car">Car</option>
                        <option value="public">Public Transportation</option>
                        <option value="walk">Walking</option>
                    {% endif %}
                </select>
            </div>
            <div class="form-group row">
                <label class="col" type='text' name="description">Description:</label>
                <textarea class="col" name="description" cols="30" rows="10" >{{trip.description}}</textarea>
            </div>
            <input type="hidden" name="organizer" value="{{request.session.user_id}}">
            <button class="btn btn-primary mx-auto" type="submit">Submit</button>
        </form>
    </main>
</body>
</html>

triplanner/apps/trips/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <title>Triplanner - Name</title>
</head>
<body>
    <header>
        <div class="d-flex justify-content-between">
            <h1 class="display-1">Hi, {{request.session.name}}!</h1>
            <!-- Pending Invites added in the middle if black belt -->
            <p class="align-self-end"><a href="{% url 'trips:new' %}">Add Trip</a> | <a href="{% url 'users:index' %}">Logout</a></p>
        </div>
        <!-- <p>You have [X] trips that you are planning to go! You also have [Y] trips to confirm invitation (Black Belt).</p> -->
    </header>
    <main class="my-5">
        {% if all_trips %}
            <h3 class="my-5">Here are your trips:</h3>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>Destination</th>
                        <!-- <th>Days Planned</th> -->
                        <th>Mode of Transportation</th>
                        <th>Organizer</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- for loop on trips -->
                    {% for trip in all_trips %}
                        <tr>
                            <td>{{trip.destination}}</td>
                            <!-- <td>[Max days for events table]</td> -->
                                {% if trip.transportation == 'car' %}
                                    <td>Car</td>
                                {% elif trip.transportation == 'walk' %}
                                    <td>Walking</td>
                                {% elif trip.transportation == 'public' %}
                                    <td>Public Transportation</td>
                                {% endif %}
                            <td>{{trip.organizer.name}}</td>
                            <!-- Add decline if Black Belt -->
                            <td><a href="/trips/{{trip.id}}">View</a>{% if trip.organizer.id == request.session.user_id %} | <a href="/trips/{{trip.id}}/edit">Edit</a> | <a href="/trips/{{trip.id}}/delete">Cancel</a> {% endif %}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h3>You do not have any trips planned</h3>
        {% endif %}
    </main>
</body>
</html>